# Generated by Django 5.0.2 on 2024-07-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_client', models.EmailField(help_text='напишите почту', max_length=150, verbose_name='почта')),
                ('name', models.CharField(help_text='напишите ФИО', max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, help_text='напишите комментарий', null=True, verbose_name='комментарии')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
